### PR TITLE
qwen2 architecture definition

### PR DESCRIPTION
**Pull request by thomasgauthier**
I added a json definition for the new Qwen model family (`Qwen2ForCausalLM`).

It might be missing keys, I'm not sure if it needs `procedural_spaces` as it has residual connections.

Nonetheless I was able successfully create a passthrough merge with this definition

### CODE REVIEW

**Comment by cg123** [comment]
Thanks for the PR! This looks good to me.

The `procedural_spaces` stuff is optional information to enable some upcoming merge methods I'm planning to implement - and it'll probably change by the time those come in anyway. Definitely no need to bother with it for now.

**Comment by DumoeDss** [comment]
Hey, I found It has some error with qwen2.
When I try to merge qwen1.5-7B and yi-6B, it will be error:
`Tensor model.layers.31.self_attn.v_proj.bias required but not present in model Yi-6B`

**Comment by v-prgmr** [comment]
@DumoeDss  I experience a similar error for phi-2 
`RuntimeError: Tensor model.layers.31.mlp.fc2.weight required but not present in model `

**Comment by Double-bear** [comment]
> Hey, I found It has some error with qwen2. When I try to merge qwen1.5-7B and yi-6B, it will be error: `Tensor model.layers.31.self_attn.v_proj.bias required but not present in model Yi-6B`

hello, have you solved this problem? How did you solve it?

**Comment by DumoeDss** [comment]
> > Hey, I found It has some error with qwen2. When I try to merge qwen1.5-7B and yi-6B, it will be error: `Tensor model.layers.31.self_attn.v_proj.bias required but not present in model Yi-6B`
> 
> hello, have you solved this problem? How did you solve it?

No, I give up.

**Comment by meiyiyeshi** [comment]
I want to add a new schema to it, but I don't know how to make json, how do you make a new qwen2.json?

**Pull request merged**
