### PR TITLE
Generic Sparsification Rescaling

### PR DESCRIPTION
**Pull request by MonsterAzi**
According to the [DARE paper](https://arxiv.org/pdf/2311.03099.pdf), rescaling allows for the sparsified tensor to approximate the original tensor. In the paper, this statement is made:
> We have also tried to combine MP with the rescale operation but got worse results than using MP separately. This is because MP removes parameters with smaller magnitudes and retains certain parameters with the largest magnitudes. Simply rescaling the remaining ones would destroy the original embeddings and result in unpredictable performance.
They claim that rescaling MP results in worse performance, but according to their theory, it should work. I believe that that they may have used the same rescaling operation as in the DARE method. However, the simple rescaling method, 1/density, used for DARE only works due to dropping making the sum of the weights equal to the sum times the density. For sparsification methods that do not use random dropping, the necessary rescaling changes based on the distribution of value in the weights.

In is due to this that I have implemented a generic rescaling method. This also cleans up some of the code (No more rescaled random). To keep compatibility, TIES still has no rescaling by default, but by adding `rescale: true` to the parameters, you can enable it. Below is a test using it:

<table>
<tr>
 <td>Model
 <td>MMLU
 <td>ARC
 <td>Winogrande
<tr>
 <td>TIES (rescaled)
 <td>51.08%
 <td>50.85%
 <td>75.53%
<tr>
 <td>DARE TIES
 <td>48.08%
 <td>45.39%
 <td>76.56%
</table>

This is not meant as proof that this method works. I am making this change mostly to help make future development of sparsification methods easier, since this rescaling algorithm works regardless of the sparsification method. (Technically DARE could even be switched to use it, but finding the necessary multiplier is more computationally expensive than the simpler implementation that is only available with dropping.)

### CODE REVIEW

**Comment by MonsterAzi** [comment]
Please review the code prior. I am not the most familiar with programming like this, so there may be mistakes or easy speed-ups possible.

**Comment by cg123** [comment]
This is a good idea, thanks for the PR!

I think this will be a good thing to add to mergekit but as is it looks like it changes the behavior of DARE - rerunning an old merge config with the same random seed would give a different result. It'd be good to keep the behavior of the `dare_ties` and `dare_linear` modes unchanged. A good way to do this might be to change `rescale:` to `rescale_method:` and have both the naive density scaling and the sum-based method as options.

Your thoughts here?

**Comment by MonsterAzi** [comment]
Thanks for the quick reply. ☺️

The generic rescaling is implemented as a separate function that the sparsification functions can call. This means that each sparsification function can choose can use it or define their own. In this branch, I've just added calling of the function to magnitude pruning. DARE retains its original code.

However, I will attempt to verify that my branch doesn't affect DARE's rescaling. I should be able to post results tomorrow.

**Comment by MonsterAzi** [comment]
Here is some real test results showing that actual end results aren't affected: (dropping is random, so there is some difference obviously)

<table>
<tr>
 <td>Model
 <td>MMLU
 <td>ARC
 <td>Winogrande
<tr>
 <td>DARE TIES (Before)
 <td>51.92%
 <td>51.16%
 <td>76.64%
<tr>
 <td>DARE TIES (After)
 <td>52.00%
 <td>50.86%
 <td>76.01%
</table>

And here is an image of the print from merging, showing that the tensors are correctly rescaled by DARE's implementation of rescaling, rather than my generic implementation:
image

**Comment by cg123** [comment]
You're right - I misread the diff, sorry! This doesn't change the behavior of DARE.

For future reference, if you want to test for equality with the randomized methods you can pass `--random-seed <number>` to get reproducible results.

Thanks for the PR!

**Pull request merged**
